import{createServer}from'node:http';import{randomUUID}from'node:crypto';import{WebSocketServer,WebSocket}from'ws';import{RoomStore,publicRoom}from'./core.mjs';
const port=Number(process.env.PORT||8787),rooms=new RoomStore(),clients=new Map(),origins=new Set((process.env.RUYD_ORIGINS||'tauri://localhost,http://localhost:1420,http://127.0.0.1:1420').split(','));
const send=(ws,v)=>ws.readyState===WebSocket.OPEN&&ws.send(JSON.stringify(v)),name=v=>String(v||'Player').trim().slice(0,32)||'Player';
function broadcast(room,type='room'){for(const c of room.clients.values())send(c.ws,{type,room:publicRoom(room,c.id)})}
function leave(id){const room=rooms.leave(id);clients.delete(id);if(room?.clients.size)broadcast(room,'presence')}
const server=createServer((req,res)=>{if(req.url==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,service:'ruyd-signaling'}))}res.writeHead(404).end('Not found')});
const wss=new WebSocketServer({noServer:true,maxPayload:16384});
server.on('upgrade',(req,socket,head)=>{if(req.headers.origin&&!origins.has(req.headers.origin))return socket.destroy();wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws))});
wss.on('connection',ws=>{const id=randomUUID();clients.set(id,{id,ws,name:'Player'});send(ws,{type:'hello',id});ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return send(ws,{type:'error',code:'bad_json'})}const c=clients.get(id);if(!c)return;if(m.type==='create'||m.type==='join'){if(rooms.roomFor(id))return send(ws,{type:'error',code:'already_connected'});c.name=name(m.name);try{const room=m.type==='create'?rooms.create(c):rooms.join(m.code,c);if(!room)return send(ws,{type:'error',code:'room_not_found'});return broadcast(room)}catch(e){return send(ws,{type:'error',code:e.message})}}const room=rooms.roomFor(id);if(!room)return send(ws,{type:'error',code:'not_connected'});if(m.type==='chat'){const text=String(m.text||'').trim().slice(0,500);if(!text)return;const packet={type:'chat',message:{id:randomUUID(),senderId:id,senderName:c.name,text,sentAt:Date.now()}};for(const p of room.clients.values())send(p.ws,packet)}else if(m.type==='signal'){const p=room.clients.get(String(m.targetId));if(p)send(p.ws,{type:'signal',senderId:id,payload:m.payload})}else if(m.type==='leave')leave(id)});ws.on('close',()=>leave(id));ws.on('error',()=>leave(id))});
setInterval(()=>rooms.cleanup(),60000).unref();server.listen(port,'0.0.0.0',()=>console.log(`Ruyd listening on :${port}`));export{server};
