import './style.css';
type Peer={id:string;name:string;virtualIp:string;self:boolean;host:boolean};
type Chat={id:string;senderId:string;senderName:string;text:string;sentAt:number};
type Room={code:string;expiresAt:number;peers:Peer[]};
type Mode='idle'|'connecting'|'connected'|'error';
const app=document.querySelector<HTMLDivElement>('#app')!;
const signalUrl=(import.meta.env.VITE_SIGNAL_URL as string|undefined)||`ws://127.0.0.1:8787`;
const playerName=localStorage.getItem('ruyd-name')||`Player ${Math.floor(100+Math.random()*900)}`;
let socket:WebSocket|null=null,mode:Mode='idle',room:Room|null=null,messages:Chat[]=[],error='',chatOpen=false;
const esc=(v:string)=>v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const send=(value:unknown)=>socket?.readyState===WebSocket.OPEN&&socket.send(JSON.stringify(value));
function connect(action:'create'|'join',code?:string){
 mode='connecting';error='';render();socket?.close();socket=new WebSocket(signalUrl);
 socket.addEventListener('open',()=>send({type:action,code,name:playerName}));
 socket.addEventListener('message',event=>{const packet=JSON.parse(event.data);
  if(packet.type==='room'||packet.type==='presence'){room=packet.room;mode='connected';render()}
  else if(packet.type==='chat'){messages.push(packet.message);render()}
  else if(packet.type==='error'){mode='error';error=({room_not_found:'That invite code is invalid or expired.',room_full:'That room is full.',already_connected:'You are already connected.'}as Record<string,string>)[packet.code]||'Could not connect.';render()}
 });
 socket.addEventListener('close',()=>{if(mode==='connected'){mode='error';error='Connection lost. Check the Ruyd service and try again.';room=null;render()}});
}
function leave(){send({type:'leave'});socket?.close();socket=null;mode='idle';room=null;messages=[];chatOpen=false;render()}
function shell(body:string){return `<main><header><div class="brand"><svg viewBox="0 0 32 32"><path d="M8 7.5h8.8a7.2 7.2 0 0 1 0 14.4H14l5.4 5.1h-5.8L5 18.6V7.5h3Zm3 5v5.4h5.5a2.7 2.7 0 0 0 0-5.4H11Z"/></svg><span>Ruyd</span></div><span class="service ${mode}">${mode==='connected'?'Online':mode==='connecting'?'Connecting…':'Ready'}</span></header>${body}<footer><span class="shield">◆</span> Private room · Regular internet stays untouched</footer></main>`}
function home(){return shell(`<section class="hero"><div class="status-orb"><i></i></div><p class="eyebrow">READY WHEN YOU ARE</p><h1>Play together.\nLike you’re in the same room.</h1><p class="sub">Start a room or paste the one code your friend sent you.</p></section>${error?`<p class="error-banner">${esc(error)}</p>`:''}<section class="actions"><button class="primary" id="host"><span class="button-icon">＋</span><span><b>Start hosting</b><small>Create a private room</small></span><em>→</em></button><button class="secondary" id="join"><span class="button-icon">↗</span><span><b>Join a friend</b><small>Paste their invite code</small></span><em>→</em></button></section><section class="how"><h2>Three steps. That’s it.</h2><ol><li><span>1</span><p><b>One person hosts</b><small>Ruyd creates a private room.</small></p></li><li><span>2</span><p><b>Share one code</b><small>Send it through your usual chat.</small></p></li><li><span>3</span><p><b>Open test chat</b><small>Confirm everyone can communicate.</small></p></li></ol></section>`)}
function roomView(){if(!room)return home();return shell(`<section class="hero active room-hero"><div class="status-orb"><i></i></div><p class="eyebrow">ROOM ONLINE</p><h1>${room.peers.some(p=>p.self&&p.host)?'Your room is live':'Connected to room'}</h1></section><section class="room"><label>INVITE CODE</label><div class="code"><strong>${room.code}</strong><button id="copy">Copy</button></div><p>Only share this code with people you trust.</p></section><section class="peers"><div class="section-title"><h2>In this room</h2><span>${room.peers.length} connected</span></div>${room.peers.map(p=>`<div class="peer"><span class="avatar">${esc(p.name[0]||'?')}</span><p><b>${esc(p.name)}${p.self?' <small>(you)</small>':''}</b><span>${p.virtualIp}</span></p><em>${p.host?'Host':'Online'}</em></div>`).join('')}<button class="chat-launch" id="chat">⌁ Open test chat ${messages.length?`<span>${messages.length}</span>`:''}</button><button class="stop" id="leave">${room.peers.some(p=>p.self&&p.host)?'Stop hosting':'Disconnect'}</button></section>${chatOpen?chat():''}`)}
function chat(){return `<div class="modal"><div class="scrim" id="close-chat"></div><section class="dialog"><button class="close" id="chat-x">×</button><p class="eyebrow">LIVE CONNECTION TEST</p><h2>Room chat</h2><p>If friends' messages arrive here, your Ruyd connection works.</p><div class="messages">${messages.length?messages.map(m=>`<div class="message ${room?.peers.find(p=>p.self)?.id===m.senderId?'mine':''}"><small>${esc(m.senderName)}</small><p>${esc(m.text)}</p></div>`).join(''):'<div class="empty-chat">No messages yet.<br/>Say hello to test the room.</div>'}</div><form id="chat-form" class="chat-form"><input name="message" maxlength="500" autocomplete="off" placeholder="Type a message…" autofocus><button class="primary compact">↑</button></form></section></div>`}
function joinDialog(){app.insertAdjacentHTML('beforeend',`<div class="modal" id="join-modal"><div class="scrim" id="cancel-join"></div><section class="dialog"><button class="close" id="join-x">×</button><p class="eyebrow">JOIN A PRIVATE ROOM</p><h2>Paste your invite code</h2><form id="join-form"><input name="code" maxlength="14" autocomplete="off" placeholder="XXXXX-XXXXXXXX" autofocus><button class="primary compact">Connect</button></form></section></div>`);const close=()=>document.querySelector('#join-modal')?.remove();document.querySelector('#cancel-join')?.addEventListener('click',close);document.querySelector('#join-x')?.addEventListener('click',close);document.querySelector('#join-form')?.addEventListener('submit',e=>{e.preventDefault();const code=new FormData(e.currentTarget as HTMLFormElement).get('code')?.toString();if(code){close();connect('join',code)}})}
function bind(){document.querySelector('#host')?.addEventListener('click',()=>connect('create'));document.querySelector('#join')?.addEventListener('click',joinDialog);document.querySelector('#copy')?.addEventListener('click',async e=>{await navigator.clipboard.writeText(room?.code||'');(e.currentTarget as HTMLElement).textContent='Copied ✓'});document.querySelector('#leave')?.addEventListener('click',leave);document.querySelector('#chat')?.addEventListener('click',()=>{chatOpen=true;render()});const close=()=>{chatOpen=false;render()};document.querySelector('#close-chat')?.addEventListener('click',close);document.querySelector('#chat-x')?.addEventListener('click',close);document.querySelector('#chat-form')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement,text=new FormData(form).get('message')?.toString().trim();if(text){send({type:'chat',text});form.reset()}})}
function render(){app.innerHTML=mode==='connected'?roomView():home();bind();if(chatOpen){const box=document.querySelector('.messages');if(box)box.scrollTop=box.scrollHeight}}
render();
