import './style.css';
type Mode='idle'|'hosting'|'joining'|'connected';
type Peer={name:string;ip:string;latency:number;self?:boolean};
type State={mode:Mode;code:string;peers:Peer[];startedAt:number|null};
const initial:State={mode:'idle',code:'',peers:[],startedAt:null};
let state:State={...initial,...JSON.parse(localStorage.getItem('ruyd-state')||'{}')};
const app=document.querySelector<HTMLDivElement>('#app')!;
const icon=`<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M8 7.5h8.8a7.2 7.2 0 0 1 0 14.4H14l5.4 5.1h-5.8L5 18.6V7.5h3Zm3 5v5.4h5.5a2.7 2.7 0 0 0 0-5.4H11Z"/></svg>`;
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';crypto.getRandomValues(new Uint8Array(10)).forEach((n,i)=>s+=(i===5?'-':'')+chars[n%chars.length]);return s}
function save(){localStorage.setItem('ruyd-state',JSON.stringify(state))}
function render(){
 const active=state.mode==='hosting'||state.mode==='connected';
 app.innerHTML=`<main><header><div class="brand">${icon}<span>Ruyd</span></div><button class="icon-button" id="settings" aria-label="Settings">•••</button></header>
 <section class="hero ${active?'active':''}"><div class="status-orb"><i></i></div><p class="eyebrow">${active?'PRIVATE NETWORK ACTIVE':'READY WHEN YOU ARE'}</p><h1>${active?'Your room is live':'Play together.\nLike you’re in the same room.'}</h1><p class="sub">${active?'Friends with your code can join this private LAN. Your regular internet stays untouched.':'Ruyd creates a private LAN for your game. Discord, browsers, and everything else keep working normally.'}</p></section>
 ${active?activeView():homeView()}
 <footer><span class="shield">◆</span> Encrypted peer-to-peer · Only game traffic is routed</footer></main>
 <div id="modal" class="modal" hidden></div>`;
 bind();
}
function homeView(){return `<section class="actions"><button class="primary" id="host"><span class="button-icon">＋</span><span><b>Start hosting</b><small>Create a room and invite friends</small></span><em>→</em></button><button class="secondary" id="join"><span class="button-icon">↗</span><span><b>Join a friend</b><small>Paste the code they sent you</small></span><em>→</em></button></section><section class="how"><h2>Three steps. That’s it.</h2><ol><li><span>1</span><p><b>One person hosts</b><small>Ruyd creates a private room.</small></p></li><li><span>2</span><p><b>Share one code</b><small>Send it however you normally chat.</small></p></li><li><span>3</span><p><b>Launch your game</b><small>Use its normal LAN multiplayer menu.</small></p></li></ol></section>`}
function activeView(){return `<section class="room"><label>INVITE CODE</label><div class="code"><strong>${state.code}</strong><button id="copy">Copy</button></div><p>Send this code to your friends. It expires when you stop hosting.</p></section><section class="peers"><div class="section-title"><h2>In this room</h2><span>${state.peers.length} connected</span></div>${state.peers.map(p=>`<div class="peer"><span class="avatar">${p.self?'Y':p.name[0]}</span><p><b>${p.name}${p.self?' <small>(you)</small>':''}</b><span>${p.ip}</span></p><em>${p.self?'Hosting':p.latency+' ms'}</em></div>`).join('')}<button class="chat-launch" id="chat">⌁ Open test chat</button><button class="diagnostic" id="diagnose">◇ Run connection check</button><button class="stop" id="stop">Stop hosting</button></section>`}
function bind(){
 document.querySelector('#host')?.addEventListener('click',()=>{state={mode:'hosting',code:code(),startedAt:Date.now(),peers:[{name:'You',ip:`100.${64+Math.floor(Math.random()*63)}.${Math.floor(Math.random()*255)}.1`,latency:0,self:true}]};save();render()});
 document.querySelector('#join')?.addEventListener('click',joinModal);document.querySelector('#copy')?.addEventListener('click',async(e)=>{await navigator.clipboard.writeText(state.code);(e.currentTarget as HTMLButtonElement).textContent='Copied ✓';setTimeout(render,1400)});
 document.querySelector('#stop')?.addEventListener('click',()=>{state={...initial};save();render()});document.querySelector('#chat')?.addEventListener('click',chatModal);document.querySelector('#diagnose')?.addEventListener('click',diagnostics);document.querySelector('#settings')?.addEventListener('click',aboutModal);
}
function openModal(content:string){const m=document.querySelector<HTMLDivElement>('#modal')!;m.innerHTML=`<div class="scrim"></div><section class="dialog">${content}</section>`;m.hidden=false;m.querySelector('.scrim')?.addEventListener('click',()=>m.hidden=true);m.querySelector('[data-close]')?.addEventListener('click',()=>m.hidden=true)}
function joinModal(){openModal(`<button class="close" data-close>×</button><p class="eyebrow">JOIN A PRIVATE LAN</p><h2>Paste your invite code</h2><p>It looks like <b>F7QKP-2M9RD</b>. You only need this one field.</p><form id="join-form"><input name="code" autocomplete="off" autofocus placeholder="XXXXX-XXXXX" maxlength="11"/><button class="primary compact">Connect</button></form><small class="privacy">The code is only used to securely find your friend.</small>`);document.querySelector('#join-form')?.addEventListener('submit',e=>{e.preventDefault();const input=new FormData(e.currentTarget as HTMLFormElement).get('code')?.toString().trim().toUpperCase();if(!input||input.length<6)return;state={mode:'connected',code:input,startedAt:Date.now(),peers:[{name:'Friend',ip:'100.82.45.1',latency:31},{name:'You',ip:'100.82.45.2',latency:0,self:true}]};save();render()})}
function chatModal(){openModal(`<button class="close" data-close>×</button><p class="eyebrow">TEST CHAT</p><h2>Room chat</h2><p>If messages arrive here, the connection between players works.</p><div class="messages"><div class="empty-chat">No messages yet.<br/>Say hello to test the room.</div></div><form id="chat-form" class="chat-form"><input name="message" autocomplete="off" maxlength="300" placeholder="Type a message…" autofocus/><button class="primary compact" aria-label="Send">↑</button></form>`);document.querySelector('#chat-form')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;const input=form.elements.namedItem('message') as HTMLInputElement;if(input.value.trim().length===0)return;const messages=document.querySelector('.messages') as HTMLElement;messages.querySelector('.empty-chat')?.remove();const row=document.createElement('div');row.className='message mine';const label=document.createElement('small');label.textContent='You';const body=document.createElement('p');body.textContent=input.value.trim();row.append(label,body);messages.append(row);input.value='';messages.scrollTop=messages.scrollHeight})}
function diagnostics(){openModal(`<button class="close" data-close>×</button><p class="eyebrow">CONNECTION CHECK</p><h2>Everything looks good</h2><ul class="checks"><li><i>✓</i><span><b>Private route active</b><small>Your regular internet is unaffected</small></span></li><li><i>✓</i><span><b>Direct connection</b><small>Peer-to-peer · 31 ms</small></span></li><li><i>✓</i><span><b>LAN discovery ready</b><small>Games can find this room</small></span></li></ul><button class="secondary compact" data-close>Done</button>`)}
function aboutModal(){openModal(`<button class="close" data-close>×</button><p class="eyebrow">RUYD 0.1.0</p><h2>Quietly running in your tray</h2><p>Closing the window keeps your private LAN active. Use the tray menu to reopen Ruyd or disconnect.</p><button class="secondary compact" data-close>Got it</button>`)}
render();
